FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir requests -r requirements.txt

COPY . .

# Setting pythonpath to enable src module imports
ENV PYTHONPATH=/app
ENV API_URL=http://api:8000

CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
